### ISSUE TITLE
你好，请帮个忙

### ISSUE THREAD

**Issue by fengnovo** [heiyu4585/heiyu4585.github.com#1]
你好，smallProject/webpack-dev-server-proxy-test/ 的一些代码端涉及到我以前公司的一下域名信息，麻烦删除 smallProject/webpack-dev-server-proxy-test/ 里面的一下代理域名，仅供学习参考

**Comment by heiyu4585** [comment]
已删

**Comment by fengnovo** [comment]
https://github.com/heiyu4585/heiyu4585.github.com/blob/983de88621ca00461453b2510921b49fb8a5e929/smallProject/webpack-dev-server-proxy-test/webpack.config.js

**Comment by fengnovo** [comment]
没有修改完
@heiyu4585

**Comment by heiyu4585** [comment]
我试了下整个文件夹删除了,你说的链接还在
你找的是历史了吧

**Comment by fengnovo** [comment]
尝试按 https://www.jianshu.com/p/573c1d2fe9fd 的做法删除掉

**Comment by fengnovo** [comment]
这个历史文件被检测出来了，给别人带来困扰，望理解 @heiyu4585

**Comment by heiyu4585** [comment]
@fengnovo 按照你说的也删不掉..
